accounts/urls.py
from django.conf.urls import url
from .import views

app_name = 'accounts'

urlpatterns = [

    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

articles/urls.py
from django.conf.urls import url
from.import views                      #"from." means from current directory and need to import views

app_name = 'articles' #for identify ulr names in different apps

urlpatterns = [
    url(r'^$',views.article_list, name="list"), #we can simply name anything to the url ,may use the
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name="detail"),   #this slug is send to views.py(in fn article_detail) ,slug is the variable name here that take input from [w.blah blah]

]

myapp/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from.import views                      #"from." means from current directory and need to import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as art_views #there a 2 views present here thats why

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/',include('articles.urls')),#from app article urls.py file(this is how we include app url in main url)
    url(r'^accounts/',include('accounts.urls')),
    url(r'^about/$',views.about),         #about is the name of function created in views.py
    url(r'^$',art_views.article_list,name="home"),            #home page goes to .com(main domain)

]
#for image
urlpatterns += staticfiles_urlpatterns() #this is for add styles,after creating this need to edit settings.py file

#for media
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

"""
when we make any changes in models need to execute the following commands
==>python manage.py makemigrations
==>python manage.py migrate
"""
#models in python are class which represents a table in database
#each model maps to a single table in database

class Article(models.Model): #syntax in django
#title,slug etc are represents columns in table Article
    title = models.CharField(max_length=100)
    slug = models.SlugField() #slugs are used later for url names
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.jpeg', blank=True)
    author = models.ForeignKey(User,default=None)

    def __str__(self):  #for the purpose of shell(it is like inbuit fn)
        return self.title

    def snippet(self):  #for displaying some limited characters in size
        return self.body[:50] + '...etc' #after 50 characters it displays '...etc'

articles/forms.py
from django import forms
from .import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title','body','slug','thumb']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout

def signup_view(request):
    if request.method == 'POST': #if it a post request we take data and validate
        form = UserCreationForm(request.POST)
        if form.is_valid(): #to check the form is valid or not,if it is valid save to db
            user = form.save()
            #log the user in
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            #login the User
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request,'accounts/login.html', {'form':form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article #import table(or class) to display
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .import forms
#in html art,in dictionary article in general articles

def article_list(request): #for /articles/
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{ 'article':articles })#render(request(always),path)#last create a dictionary to send data to templates

def article_detail(request,slug): #for /slug/ and we capture variable 'slug' in urls.py,this slug is not db slug directly
    #return HttpResponse(slug)

    arts = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{ 'artd':arts })

@login_required(login_url="/accounts/login") #if user not loged in it blocks create option and redirect to login page
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST,request.FILES)
        if form.is_valid():
            #save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
        return render(request,'articles/article_create.html',{'form':form})

myapp/views.py
from django.http import HttpResponse #respond to user via http (i think)
from django.shortcuts import render #to render a html template

#define 2 views that provided in urls.py(about and home)
def about(request):
    #return HttpResponse("about")#send something through HttpResponse
    return render(request,'about.html')

def homepage(request):
    #return HttpResponse("homepage")#function homepage from view will fire silmry above
    return render(request,'homepage.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Login</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post"><!-- login is the url name in urls.py accounts is the app name -->
    {% csrf_token %}
    {{ form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}  
    <input type="submit" name="submit" value="Login">
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>signup</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="submit" value="Signup">
  </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
  <div class="create-article">
    <h2>Create an Awesome New Article Here</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <input type="submit" value="create">
    </form>
  </div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content %}

<div class="article-detail">
  <div class="article">
    <img src="{{ artd.thumb.url }}/"> <!-- when use img field in model use url last -->
    <h2>{{ artd.title }}</h2>
    <p>{{ artd.body }}</p>
    <p>{{ artd.date }}</p>
  </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}

<!-- commending the following because we use base templates
 {% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Article</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}"> #or href="/staric/styles.css" so above code is not req.
  </head>
  <body> -->
    <h1>Article list</h1>
    <div class="articles">
      {% for art in article %}
        <div class="art">
          <h2><a href="{% url 'articles:detail' slug=art.slug %}">{{ art.title }}</a></h2> <!--here articles is the app name  -->
          <p>{{ art.snippet }}</p>
          <p>{{ art.date }}</p>
        </div>
      {% endfor %}
    </div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Aboutpage</title>
  </head>
  <body>
    <h1>This is the about page</h1>
    <p>Welcome to django about</p>
  </body>
</html>

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Article</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}"><!--or href="/staric/styles.css" so above code is not req. -->
  </head>
  <body>
    <div class="wrapper">
      <!-- in the below case we can also use 'home' instead of 'articles:list' -->
      <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo2.jpg' %}"/></a></h1> <!--django looks a url named list. -->
      <nav>
        <ul>
          {% if user.is_authenticated %}
                <li>
                <form class="logout-link" action="{% url  'accounts:logout' %}" method="POST">
                  {% csrf_token %}
                  <button type="submit">Logout</button>
                </form>
              </li>
              <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
          {% else %}
              <li><a href="{% url 'accounts:login' %}">Login</a></li>
              <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
          {% endif %}
        </ul>
      </nav>
      {% block content %} <!--create a block named content -->
      {% endblock %}
    </div>
  </body>
</html>

templates/homepage.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the home page</h1>
    <p>Welcome to django homepage</p>
  </body>
</html>